import React, { useMemo } from 'react';
import { FileText, Calendar, Activity, Pill, User, AlertTriangle } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const DoctorSummaryView = ({ user, disease, metrics, insights, medications }) => {

    // Filter active medications relevant to this disease (naive filter or show all)
    // For now, show all active meds
    const activeMeds = (medications || []).filter(m => m.status === 'active');

    // Calculate quick stats
    const stats = useMemo(() => {
        if (!metrics || metrics.length === 0) return null;
        const values = metrics.map(m => Number(m.value));
        const avg = (values.reduce((a, b) => a + b, 0) / values.length).toFixed(1);
        const max = Math.max(...values);
        const min = Math.min(...values);
        const lastDate = new Date(metrics[0].timestamp.seconds * 1000).toLocaleDateString();
        return { avg, max, min, lastDate, count: values.length };
    }, [metrics]);

    const chartData = useMemo(() => {
        // Small sparkline data (last 15 points)
        return metrics.slice(0, 15).map(m => ({
            date: new Date(m.timestamp.seconds * 1000).toLocaleDateString(),
            val: m.value
        })).reverse();
    }, [metrics]);

    return (
        <div className="bg-white text-slate-900 p-8 max-w-4xl mx-auto rounded-none print:p-0 print:max-w-none">

            {/* Header - Clinical Formal Style */}
            <div className="border-b-2 border-slate-900 pb-4 mb-6 flex justify-between items-start">
                <div>
                    <h1 className="text-2xl font-bold uppercase tracking-tight">Clinical Summary Report</h1>
                    <div className="text-sm text-slate-500 mt-1">Generated by Curebird Patient Intelligence Platform</div>
                </div>
                <div className="text-right">
                    <div className="font-bold text-lg">{user?.displayName || 'Patient Name'}</div>
                    <div className="text-sm text-slate-600">Generated: {new Date().toLocaleDateString()}</div>
                    <div className="text-xs text-slate-400 mt-1">ID: {user?.uid?.slice(0, 8)}...</div>
                </div>
            </div>

            {/* Condition Overview */}
            <div className="mb-8">
                <h2 className="text-sm font-bold uppercase text-slate-500 mb-2 border-b border-slate-200 pb-1 flex items-center gap-2">
                    <Activity size={14} /> Condition Profile
                </h2>
                <div className="grid grid-cols-4 gap-4 bg-slate-50 p-4 rounded-lg border border-slate-200">
                    <div>
                        <span className="block text-xs text-slate-500 uppercase">Condition</span>
                        <span className="font-bold text-lg">{disease.name}</span>
                    </div>
                    <div>
                        <span className="block text-xs text-slate-500 uppercase">Diagnosis Date</span>
                        <span className="font-medium">{disease.diagnosisDate}</span>
                    </div>
                    <div>
                        <span className="block text-xs text-slate-500 uppercase">Status</span>
                        <span className="font-medium capitalize">{disease.status}</span>
                    </div>
                    <div>
                        <span className="block text-xs text-slate-500 uppercase">Severity</span>
                        <span className="font-medium capitalize">{disease.severity}</span>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">

                {/* Metric Statistics */}
                <div>
                    <h2 className="text-sm font-bold uppercase text-slate-500 mb-3 border-b border-slate-200 pb-1 flex items-center gap-2">
                        <TrendingUpIcon /> Recent Vitals (n={stats?.count})
                    </h2>

                    {stats ? (
                        <div className="space-y-4">
                            <div className="grid grid-cols-3 gap-2 text-center">
                                <div className="bg-slate-100 p-2 rounded">
                                    <div className="text-xs text-slate-500">Average</div>
                                    <div className="font-mono font-bold text-xl">{stats.avg}</div>
                                </div>
                                <div className="bg-slate-100 p-2 rounded">
                                    <div className="text-xs text-slate-500">Max</div>
                                    <div className="font-mono font-bold text-xl">{stats.max}</div>
                                </div>
                                <div className="bg-slate-100 p-2 rounded">
                                    <div className="text-xs text-slate-500">Min</div>
                                    <div className="font-mono font-bold text-xl">{stats.min}</div>
                                </div>
                            </div>

                            {/* Mini Chart for Print */}
                            <div className="h-40 w-full border border-slate-100 rounded bg-slate-50 p-2">
                                <ResponsiveContainer width="100%" height="100%">
                                    <LineChart data={chartData}>
                                        <XAxis dataKey="date" hide />
                                        <YAxis hide domain={['auto', 'auto']} />
                                        <Line type="monotone" dataKey="val" stroke="#0f172a" strokeWidth={2} dot={false} />
                                    </LineChart>
                                </ResponsiveContainer>
                            </div>
                        </div>
                    ) : (
                        <div className="text-sm text-slate-400 italic">No metrics recorded.</div>
                    )}
                </div>

                {/* AI Clinical Insight */}
                <div>
                    <h2 className="text-sm font-bold uppercase text-slate-500 mb-3 border-b border-slate-200 pb-1 flex items-center gap-2">
                        <BotIcon /> Clinical Observations (AI Assist)
                    </h2>
                    {insights && insights.doctorView ? (
                        <div className="bg-blue-50 border border-blue-100 p-4 rounded-lg text-sm text-slate-800">
                            <ul className="list-disc pl-4 space-y-2">
                                {insights.doctorView.points.map((pt, i) => (
                                    <li key={i}>{pt}</li>
                                ))}
                            </ul>
                            <div className="mt-3 pt-2 border-t border-blue-100 text-xs text-slate-500 italic">
                                * Automated pattern detection. Not a diagnosis.
                            </div>
                        </div>
                    ) : (
                        <div className="text-sm text-slate-400 italic">No insights available.</div>
                    )}
                </div>
            </div>

            {/* Data Table (Recent 10) */}
            <div className="mb-8">
                <h2 className="text-sm font-bold uppercase text-slate-500 mb-3 border-b border-slate-200 pb-1 flex items-center gap-2">
                    <FileText size={14} /> Recent Logs
                </h2>
                <table className="w-full text-sm text-left">
                    <thead className="bg-slate-100 text-slate-600 font-semibold uppercase text-xs">
                        <tr>
                            <th className="px-4 py-2">Date</th>
                            <th className="px-4 py-2">Time</th>
                            <th className="px-4 py-2">Value</th>
                            <th className="px-4 py-2">Unit</th>
                            <th className="px-4 py-2">Notes</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {metrics.slice(0, 10).map((m, i) => (
                            <tr key={m.id} className="hover:bg-slate-50">
                                <td className="px-4 py-2">{new Date(m.timestamp.seconds * 1000).toLocaleDateString()}</td>
                                <td className="px-4 py-2 text-slate-500">{new Date(m.timestamp.seconds * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</td>
                                <td className="px-4 py-2 font-mono font-bold">{m.value}</td>
                                <td className="px-4 py-2 text-slate-500">{m.unit}</td>
                                <td className="px-4 py-2 text-slate-400 italic">{m.notes || '-'}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Footer */}
            <div className="mt-12 pt-6 border-t border-slate-200 text-center text-xs text-slate-400">
                <p>Report generated by Curebird. This document contains private medical information.</p>
            </div>

        </div>
    );
};

// Icons helper
const TrendingUpIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline><polyline points="17 6 23 6 23 12"></polyline></svg>;
const BotIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2a2 2 0 0 1 2 2v2a2 2 0 0 1-2 2v0a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2z" /><rect width="18" height="12" x="3" y="10" rx="2" /><circle cx="12" cy="16" r="2" /><path d="M5 22h14" /><path d="M5 10V4a2 2 0 0 0-2-2" /><path d="M19 10V4a2 2 0 0 1 2-2" /></svg>;

export default DoctorSummaryView;
